language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4

env:
  - MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli

before_install:
- composer selfupdate
- composer config -g github-oauth.github.com $GITHUB_API_TOKEN

install:
  # We do this funny song and dance to mimic how a Moodle plugin would be run.
  - composer install -n
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)
  - cd ../..

  # Finally, the standard install step.
  - moodle-plugin-ci install

script:
  - phpunit -c moodlerooms/moodle-plugin-ci --coverage-clover coverage.clover
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat

after_success:
  - ocular code-coverage:upload --format=php-clover coverage.clover
