language: php

sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - MUSTACHE_IGNORE_NAMES=broken.mustache
    - DB=pgsql
    - MOODLE_BRANCH=master

install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - make init

  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)

  # Finally, the standard install step.
  - moodle-plugin-ci install

script:
  - make test-phpunit

  # This is basically "integration" testing.
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat

jobs:
  include:
    - stage: Tests
      addons: skip
      install:
        - phpenv config-rm xdebug.ini
        - make init
      script:
        - make validate
      after_script:
        - make upload-code-coverage
    - stage: Integration tests
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.6
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli
    - stage: Deploy
      addons: skip
      install: skip
      script: skip
      before_deploy:
        - make build/moodle-plugin-ci.phar
        - php build/moodle-plugin-ci.phar list
