language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0

matrix:
 allow_failures:
  - php: 7.0

env:
 global:
  - COMPONENT=mod_example # Change this line!  It is the Moodle component name of your plugin.
  - COMPONENT_DIR=mod/example # Change this line! It is the directory of where your plugin is installed into Moodle.
  - MOODLE_BRANCH=MOODLE_29_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

sudo: false

before_install:
- composer config -g github-oauth.github.com $GITHUB_API_TOKEN

install:
  - cd ../..
  - git clone git://github.com/mrmark/moodle-travis-plugin helper
  - composer install --working-dir helper
  - helper/bin/phing -f helper/install.xml

script:
  - helper/bin/phing -f helper/script.xml PHPLint
  - helper/bin/phing -f helper/script.xml PHPCPD
  - helper/bin/phing -f helper/script.xml PHPMD
  - helper/bin/phing -f helper/script.xml CodeChecker
  - helper/bin/phing -f helper/script.xml CSSLint
  - helper/bin/phing -f helper/script.xml Shifter
  - helper/bin/phing -f helper/script.xml JSHint
  - helper/bin/phing -f helper/script.xml PHPUnit
  - helper/bin/phing -f helper/script.xml Behat